---
- name: Add openjdk-r ppa repository
  apt_repository:
    repo: "ppa:openjdk-r/ppa"
    state: present
  tags:
    - logstash

- name: Add logstash apt repository key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  tags:
    - logstash

- name: Install logstash apt repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
  tags:
    - logstash

- name: Update repository cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - logstash

- name: Install logstash package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "openjdk-8-jre"
    - "logstash"
  tags:
    - logstash

- name: Enable logstash service
  service:
    name: logstash
    state: started
    enabled: yes
  tags:
    - logstash

- name: Ensure the logstash configuration directory exists
  file:
    path: /etc/logstash/conf.d
    state: directory
  tags:
    - logstash

- name: Add logstash UDP input
  file:
    template:
      src: 00-udp-input.conf.j2
      dest: /etc/logstash/conf.d/00-udp-input.conf
      owner: root
      group: root
      mode: 0644
  tags:
    - logstash
  notify:
    - restart logstash

- name: Add logstash ES output
  file:
    template:
      src: 10-elasticsearch-output.conf.j2
      dest: /etc/logstash/conf.d/10-elasticsearch-output.conf
      owner: root
      group: root
      mode: 0644
  tags:
    - logstash
  notify:
    - restart logstash
