---
# handlers file for slave

- name: remove slave state
  file:
    path: "/var/lib/mesos/meta/slaves/latest"
    state: absent
  notify:
    - restart mesos-slave

- name: restart mesos-slave
  service:
    name: mesos-slave
    enabled: yes
    state: restarted

- name: restart docker
  service:
    name: docker
    enabled: yes
    state: restarted

- name: restart consul
  service:
    name: consul
    enabled: yes
    state: restarted

- name: restart consul-template
  service:
    name: consul-template
    state: restarted
