---

- hosts: all
  sudo: yes
  roles:
    - common
    - consul
    - tersmitten.postfix

- hosts: mesos-master
  tasks: []
  tags:
    - always

- hosts: mesos-slave
  tasks: []
  tags:
    - always

- hosts: storage
  tasks: []
  tags:
    - always

- hosts: openvpn
  sudo: yes
  roles:
    - openvpn-firewall
    - Stouts.openvpn
  tags:
    - openvpn

- hosts: storage
  sudo: yes
  roles:
    - storage
  vars:
    gluster_volumes:
      - marathon
      - jenkins

- hosts: mesos-master
  sudo: yes
  roles:
    - mesos-common
    - mesos-master
  vars:
    paas_apps_fqdn: 'paas.mozilla.community'
  tags:
    - mesos-master

- hosts: mesos-slave
  sudo: yes
  roles:
    - mesos-common
    - mesos-slave
  vars:
    marathon_gluster_volume: 'marathon'
    marathon_gluster_mountpoint: '/srv/marathon'
  tags:
    - mesos-slave

- hosts: jenkins
  sudo: yes
  roles:
    - jenkins
  tags:
    - jenkins
  vars:
    jenkins_gluster_volume: 'jenkins'
    jenkins_gluster_mountpoint: '/opt/jenkins'
