---

#- hosts: all
#  sudo: yes
#  roles:
#    - common

- hosts: mesos-master
  tasks: []
  tags:
    - always

- hosts: mesos-slave
  tasks: []
  tags:
    - always

- hosts: storage
  tasks: []
  tags:
    - always

- hosts: openvpn
  sudo: yes
  roles:
    - openvpn-firewall
    - Stouts.openvpn
  vars:
    openvpn_use_pam: yes
    openvpn_clients: [partinfra-vpn]

- hosts: storage
  sudo: yes
  roles:
    - storage
  vars:
    gluster_volumes:
      - marathon

- hosts: mesos-master
  sudo: yes
  roles:
    - mesos-common
    - mesos-master
  vars:
    paas_apps_fqdn: 'paas.mozilla.community'
  tags:
    - mesos-master

- hosts: mesos-slave
  sudo: yes
  roles:
    - mesos-common
    - mesos-slave
  vars:
    marathon_gluster_volume: 'marathon'
    marathon_gluster_mountpoint: '/srv/marathon'
  tags:
    - mesos-slave
