---

- hosts: all
  sudo: yes
  roles:
    - tersmitten.postfix
    - common
    - consul
    - jnv.unattended-upgrades

- hosts: mesos-master
  tasks: []
  tags:
    - always

- hosts: mesos-slave
  tasks: []
  tags:
    - always

- hosts: storage
  tasks: []
  tags:
    - always

- hosts: openvpn
  sudo: yes
  roles:
    - openvpn-firewall
    - Stouts.openvpn
  tags:
    - openvpn

- hosts: storage
  sudo: yes
  roles:
    - storage
  vars:
    gluster_volumes:
      - marathon

- hosts: mesos-master
  sudo: yes
  roles:
    - mesos-common
    - mesos-master
  tags:
    - mesos-master

- hosts: mesos-slave
  sudo: yes
  roles:
    - mesos-common
    - mesos-slave
  tags:
    - mesos-slave

- hosts: jenkins
  sudo: yes
  roles:
    - jenkins
  tags:
    - jenkins
  vars:
    jenkins_gluster_volume: 'partinfra_jenkins'
    jenkins_gluster_mountpoint: '/opt/jenkins'
