---
# handlers file for master
- name: restart zookeeper
  service:
    name: zookeeper
    enabled: yes
    state: restarted

- name: restart mesos-master
  service:
    name: mesos-master
    enabled: yes
    state: restarted

- name: restart marathon
  service:
    name: marathon
    enabled: yes
    state: restarted

- name: restart bamboo
  service:
    name: bamboo-server
    enabled: yes
    state: restarted

- name: restart haproxy
  service:
    name: haproxy
    enabled: yes
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    enabled: yes
    state: restarted

- name: restart consul
  service:
    name: consul
    enabled: yes
    state: restarted

- name: restart consul-template
  service:
    name: consul-template
    enabled: yes
    state: restarted
