---

- name: Register mig-agent package stat
  stat:
    path: "/opt/{{ mig_agent_package }}"
  register: mig_agent_file
  tags:
    - security
    - mig


- name: Fetch mig-agent package from S3
  s3:
    aws_access_key: "{{ s3_deployment_access_key }}"
    aws_secret_key: "{{ s3_deployment_secret_key }}"
    bucket: "{{ s3_deployment_bucket }}"
    object: "{{ mig_agent_package }}"
    dest: "/opt/{{ mig_agent_package }}"
    mode: "get"
  when: mig_agent_file.stat.exists == False
  tags:
    - security
    - mig

- name: Install mig-agent
  apt:
    deb: "/opt/{{ mig_agent_package}}"
  when: mig_agent_file.stat.exists == False
  tags:
    - security
    - mig

- name: Configure mig-agent upstart service
  copy:
    src: mig_upstart.conf
    dest: /etc/init/mig.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mig
  tags:
    - security
    - mig

- name: Enable mig-agent service
  service:
    name: mig
    state: started
    enabled: yes
  tags:
    - security
    - mig
