---
- name: Install GlusterFS PPA
  apt_repository:
    repo: "ppa:gluster/glusterfs-3.7"
  tags:
    - gluster
    - jenkins

- name: Install GlusterFS client
  apt:
    name: "glusterfs-client"
    state: present
  tags:
    - gluster
    - jenkins

- name: Ensure gluster volume mountpoint exists
  file:
    path: "{{ jenkins_gluster_mountpoint }}"
    state: directory
  tags:
    - gluster
    - jenkins

- name: Mount gluster volume for jenkins persistent storage
  mount:
    name: "{{ jenkins_gluster_mountpoint }}"
    src: "{{ groups.storage[0] }}:/{{ jenkins_gluster_volume }}"
    fstype: glusterfs
    state: mounted
  tags:
    - gluster
    - jenkins

- name: Add docker deb repository keys
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: "58118E89F3A912897C070ADBF76221572C52609D"
  tags:
    - jenkins

- name: Remove (legacy) docker deb repository
  apt_repository:
    repo: "deb http://get.docker.io/ubuntu docker main"
    state: absent
  tags:
    - mesos
    - docker

- name: Add docker deb repository
  apt_repository:
    repo: "deb http://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present
  tags:
    - mesos
    - docker

- name: Update repository cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - jenkins

- name: Install apt dependencies
  apt:
    name: "{{ item }}"
    state: present
  tags:
    - jenkins
  with_items:
    - docker
    - docker-engine
    - python-pip
    - python-dev

- name: install docker-py with pip
  pip:
    name: docker-py

- name: Ensure jenkins volume folder exists
  file:
    path: "/opt/jenkins"
    state: directory
    owner: 1000
  tags:
    - jenkins

- name: start docker
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - jenkins
    - docker

- name: pull jenkins image
  docker_image:
    name: partinfra/jenkins
    tag: "{{ jenkins_release }}"

- name: Run jenkins docker
  docker:
    name: jenkins
    image: partinfra/jenkins:{{ jenkins_release }}
    state: reloaded
    pull: always
    ports:
      - "80:8080"
      - "5000:5000"
    volumes:
      - "/opt/jenkins:/var/jenkins_home"
    restart_policy: always
  tags:
    - jenkins
    - startjenkins

- name: Setup consul service and check definitions
  template:
    src: consul.json.j2
    dest: /etc/consul.d/jenkins.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul
  tags:
    - jenkins
    - consul
