---

- name: Add docker deb repository keys
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: "58118E89F3A912897C070ADBF76221572C52609D"
  tags:
    - docker

- name: Remove (legacy) docker deb repository
  apt_repository:
    repo: "deb http://get.docker.io/ubuntu docker main"
    state: absent
  tags:
    - docker

- name: Add docker deb repository
  apt_repository:
    repo: "deb http://apt.dockerproject.org/repo {{ ansible_distribution_release }} main"
    state: present
  tags:
    - docker

- name: Update repository cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - docker

- name: Install apt dependencies
  apt:
    name: "{{ item }}"
    state: present
  tags:
    - docker
  with_items:
    - docker-engine
    - python-pip
    - python-dev

- name: Install docker-py with pip
  pip:
    name: docker-py

- name: start docker
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - jenkins
    - docker
