---
- name: Enable haproxy ppa
  apt_repository:
    repo: "ppa:vbernat/haproxy-1.5"
    state: present
  tags:
    - haproxy

- name: Install java 8 repository
  apt_repository:
    repo: "ppa:webupd8team/java"
  tags:
    - zookeeper

- name: Update repository cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - zookeeper
    - bamboo
    - haproxy
    - mesos
    - marathon

- name: Auto accept oracle jdk license
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    vtype: 'select'
    value: 'true'
  tags:
    - zookeeper

- name: Install Java 8
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
  tags:
    - zookeeper

- name: Install zookeeper
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zookeeper
    - zookeeperd
  tags:
    - zookeeper

- name: Install mesosphere
  apt:
    name: mesosphere
    state: present
  tags:
    - mesos
    - marathon

- stat:
    path: "/tmp/consul_template_{{ consul_template_version }}.zip"
  register: consul_template_ver_local
  tags:
    - consul-template

- name: Install unzip
  apt:
    name: unzip
    state: present
  tags:
    - consul-template

- name: Install haproxy
  apt:
    name: "haproxy"
    state: present
  tags:
    - consul-template

- name: Download consul-template
  get_url:
    url: 'https://releases.hashicorp.com/consul-template/{{ consul_template_version }}/consul-template_{{ consul_template_version}}_linux_amd64.zip'
    dest: '/tmp/consul_template_{{ consul_template_version }}.zip'
    owner: root
    group: root
    mode: 0644
  when: consul_template_ver_local.stat.exists == False
  tags:
    - consul-template

- name: Unpack consul-template
  unarchive:
    src: '/tmp/consul_template_{{ consul_template_version }}.zip'
    dest: '/usr/local/bin'
    copy: no
    owner: root
    group: root
    mode: 0755
  when: consul_template_ver_local.stat.exists == False
  tags:
    - consul-template

- name: Create required directories for consul-template
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/consul-template.d/templates"
  tags:
    - consul-template
